# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"xplorer" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"xournalpp" = "X++"
"libreoffice" = "ï£…"
"vim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"vscode" = "ï„¡"
"visual studio code" = "ï„¡"
"code" = "ï„¡"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
